---
title: "Quick start guide for usage of netdis functions"
author: "Jack Roberts"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick start for Netdis functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Load required libraries
```{r}
# Load libraries
library("netdist")
library("purrr")
```

## Load graphs
```{r}
# Set source directory for Virus PPI graph edge files
source_dir <- system.file(file.path("extdata", "VRPINS"), package = "netdist")

# Load query graphs
graph_1 <- read_simple_graph(file.path(source_dir, "EBV.txt"),
                             format = "ncol")

graph_2 <- read_simple_graph(file.path(source_dir, "ECL.txt"),
                             format = "ncol")

# Load reference graph
# JACK - need to deal with case where ref graph not used.
ref_path <- system.file(file.path("extdata", "random", "ER_1250_10_1"), 
                        package = "netdist")
ref_graph <- read_simple_graph(ref_path, format = "ncol")
```

## Set Netdis parameters
```{r}
# Maximum graphlet size to calculate counts and netdis statistic for.
max_graphlet_size <- 4

# Ego network neighbourhood size
neighbourhood_size <- 2

# Minimum size of ego networks to consider
min_ego_nodes <- 3
min_ego_edges <- 1

# Ego network density binning parameters
min_bin_count <- 5
num_bins <- 100

# Reference graph
ref_path <- system.file(file.path("extdata", "random", "ER_1250_10_1"), 
                        package = "netdist")
ref_graph <- read_simple_graph(ref_path, format = "ncol")

```

## Compare two graphs
```{r}
# Load query graphs
source_dir <- system.file(file.path("extdata", "VRPINS"), package = "netdist")

graph_1 <- read_simple_graph(file.path(source_dir, "EBV.txt"),
                             format = "ncol")

graph_2 <- read_simple_graph(file.path(source_dir, "ECL.txt"),
                             format = "ncol")

# Calculate netdis statistics
netdis_one_to_one(graph_1, graph_2,
                  ref_graph,
                  max_graphlet_size = 4,
                  neighbourhood_size = 2,
                  min_ego_nodes = 3,
                  min_ego_edges = 1,
                  min_bin_count = 5,
                  num_bins = 100)
```

## Compare one graph to many other graphs
```{r}
# Load query graphs
source_dir <- system.file(file.path("extdata", "VRPINS"), package = "netdist")

graph_1 <- read_simple_graph(file.path(source_dir, "EBV.txt"),
                             format = "ncol")

graphs_compare <- 0

# Calculate netdis statistics
netdis_one_to_many(graph_1, graphs_compare,
                   ref_graph,
                   max_graphlet_size = 4,
                   neighbourhood_size = 2,
                   min_ego_nodes = 3,
                   min_ego_edges = 1,
                   min_bin_count = 5,
                   num_bins = 100)
```

## Do pairwise netdis calculations for many graphs
```{r}
# Load query graphs
source_dir <- system.file(file.path("extdata", "VRPINS"), package = "netdist")

graphs <- 0

# Calculate netdis statistics
netdis_many_to_many(graphs,
                   ref_graph,
                   max_graphlet_size = 4,
                   neighbourhood_size = 2,
                   min_ego_nodes = 3,
                   min_ego_edges = 1,
                   min_bin_count = 5,
                   num_bins = 100)
```