---
title: "Quick start guide for Netdis"
author: "Martin O'Reilly"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick start for Netdis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Load required libraries
```{r}
# Load libraries
library("netdist")
library("purrr")
```

## Set Netdis parameters
```{r}
# Maximum graphlet size to calculate counts for.
# We choose the specific graphlet size for the Netdis metric later.
max_graphlet_size = 4
```

## Load graphs

```{r}
# Set source directory for Virus PPI graph edge files
source_dir <- system.file(file.path("extdata", "VRPINS"), package = "netdist")
# Load query graphs
graphs <- read_simple_graphs(source_dir, format = "ncol", pattern = "*")
```

## Generate ego networks
```{r}

# Set ego network neighbourhood size
neighbourhood_size = 2
ego_networks <- purrr::map(graphs, make_named_ego_graph, 
                           order = neighbourhood_size)
```

## Count graphlets in ego networks
```{r}
ego_graphlet_counts <- purrr::map_depth(ego_networks, 2, count_graphlets_for_graph,
                              max_graphlet_size = max_graphlet_size)
```

## Define function for calculating expected counts for ego networks
Here we generate these from a reference graph.

### Generate scaled graphlet counts for reference graph.
```{r}
# Load reference graph
file <- system.file(file.path("extdata", "random", "ER_1250_10_1"), 
                    package = "netdist")
ref_graph <- read_simple_graph(file, format = "ncol")

# Generate ego networks for reference graph
ref_ego_networks <- make_named_ego_graph(ref_graph, order = neighbourhood_size)

# Count graphlets for ego networks in reference graph
ref_ego_graphlet_counts <- purrr::map(ref_ego_networks, count_graphlets_for_graph,
                              max_graphlet_size = max_graphlet_size)

# Scale ego-network graphlet counts by dividing by total number of k-tuples in
  # ego-network (where k is graphlet size)
ref_ego_graphlet_tuples <- 
    count_graphlet_tuples_ego(ref_ego_networks, max_graphlet_size = max_graphlet_size)

#ref_ego_graphlet_counts <- scale_graphlet_count(ref_ego_graphlet_counts, ref_ego_graphlet_tuples)
```
