# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Count number of co-occurences
#'
#' @param features a Matrix with doubles.
#'
#' @export
countsToDhist <- function(features) {
    .Call('_netdist_countsToDhist', PACKAGE = 'netdist', features)
}

#' @title
#' Compute EMD
NULL

#' @title
#' Compute full EMD
NULL

#'
#' @export
NetEmdConstant <- function(loc1, val1, loc2, val2) {
    .Call('_netdist_NetEmdConstant', PACKAGE = 'netdist', loc1, val1, loc2, val2)
}

#'
#' @export
NetEmdFullExhaustiveNoSmooth <- function(loc1, val1, loc2, val2) {
    .Call('_netdist_NetEmdFullExhaustiveNoSmooth', PACKAGE = 'netdist', loc1, val1, loc2, val2)
}

#' @title
#' Compute EMD
NULL

#'
#' @export
NetEmdExhaustiveMedian <- function(loc1, val1, loc2, val2) {
    .Call('_netdist_NetEmdExhaustiveMedian', PACKAGE = 'netdist', loc1, val1, loc2, val2)
}

