# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Count number of occurences
#'
#' @param features a Matrix with doubles.
#'
#' @export
countsToDhist <- function(features) {
    .Call('_netdist_countsToDhist', PACKAGE = 'netdist', features)
}

