# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Count number of occurences
#'
#' @param features A Matrix with doubles.
#'
#' @export
counts_from_observations <- function(features) {
    .Call(`_netdist_counts_from_observations`, features)
}

#' @title
#' Compute Earth Mover's Distance (EMD) between two Empirical Cumulative 
#' Density Functions (ECDFs)
#'
#' @param locations1 Locations for ECDF 1
#' @param values1 Cumulative masses for ECDF 1
#' @param locations2 Locations for ECDF 2
#' @param values2 Cumulative masses for ECDF 2
#'
#' @export
emd_fast_no_smoothing <- function(locations1, values1, locations2, values2) {
    .Call(`_netdist_emd_fast_no_smoothing`, locations1, values1, locations2, values2)
}

#' @title
#' Compute EMD
NULL

#'
#' @export
NetEmdSmoothV2 <- function(loc1, val1, binWidth1, loc2, val2, binWidth2) {
    .Call(`_netdist_NetEmdSmoothV2`, loc1, val1, binWidth1, loc2, val2, binWidth2)
}

